name: Convert CSV to JSON

on:
  push:
    paths:
      - 'csv/**/*.csv'
  pull_request:
    paths:
      - 'csv/**/*.csv'
  workflow_dispatch: # Allow manual triggering

jobs:
  convert-csv-to-json:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install google-generativeai; fi
    
    - name: Convert CSV files to JSON
      run: python convert_csv_to_json.py

    - name: Translate menus to Tamil/Hindi (Gemini)
      if: env.GEMINI_API_KEY != ''
      run: python translate_menus.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain json/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add json/
        git commit -m "Auto-update JSON files from CSV changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload JSON artifacts
      uses: actions/upload-artifact@v4
      with:
        name: json-files
        path: json/
        retention-days: 30
