name: Translate JSON to ta/hi

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: translate-json-${{ github.ref }}
  cancel-in-progress: true

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Determine changed json/en files
      id: changes
      shell: bash
      run: |
        set -e
        if [ "${{ github.event_name }}" = "push" ]; then
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'json/en/**/*.json' > changed_jsons.txt || true
        else
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          git fetch origin ${{ github.head_ref }} --depth=1 || true
          git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} -- 'json/en/**/*.json' > changed_jsons.txt || true
        fi
        json_count=$(grep -c . changed_jsons.txt || true)
        echo "json_count=$json_count" >> $GITHUB_OUTPUT
        echo "Changed json/en files:"
        cat changed_jsons.txt || true

    - name: Install dependencies for translation
      if: steps.changes.outputs.json_count != '0' && env.GEMINI_API_KEY != ''
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Translate changed menus (Gemini)
      if: steps.changes.outputs.json_count != '0' && env.GEMINI_API_KEY != ''
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python translate_menus.py --langs ta hi --from-file changed_jsons.txt

    - name: Ensure laundry JSON parity (copy only)
      if: steps.changes.outputs.json_count != '0'
      run: |
        python translate_menus.py --parity-only --from-file changed_jsons.txt --langs ta hi

    - name: Check for changes
      id: verify
      run: |
        if [ -n "$(git status --porcelain json/ta json/hi)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push translations
      if: steps.verify.outputs.changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add json/ta/ json/hi/
        git commit -m "chore(i18n): update ta/hi translations for changed json/en menus"
        git push

    - name: Upload translation artifacts (PR preview)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: json-translations
        path: |
          json/ta/
          json/hi/
        retention-days: 7
